{{- if and ( eq .Capabilities.KubeVersion.Major "1") ( le .Capabilities.KubeVersion.Minor "18" ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-rclone
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-controller-rclone-{{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role-rclone-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: csi-controller-rclone
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: external-controller-rclone-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cluster-driver-registrar-role-{{ .Release.Namespace }}
rules:
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["create", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cluster-driver-registrar-binding-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: csi-controller-rclone
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-cluster-driver-registrar-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
