{{- if and ( eq .Capabilities.KubeVersion.Major "1") ( le .Capabilities.KubeVersion.Minor "18" ) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ default "rclone" .Values.storageClass.name }}
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/no-provisioner
{{- end }}
