---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rclone-hostpath.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "rclone-hostpath.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ include "rclone-hostpath.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rclone-hostpath.fullname" . }}
        release: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      - name: {{ include "rclone-hostpath.fullname" . }}-config
        image: "{{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}"
        command:
          - cp
        args:
          - -v
          - /in/rclone.conf
          - /out/rclone.conf
        volumeMounts:
        - name: rclone-config
          mountPath: /in
          readOnly: true
        - name: config
          mountPath: /out
      - name: {{ include "rclone-hostpath.fullname" . }}-data
        image: "{{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}"
        command:
          - rm
        args:
          - -rf
          - /data/*
        volumeMounts:
        - name: data
          mountPath: /data
      terminationGracePeriodSeconds: 120
      containers:
      - name: {{ include "rclone-hostpath.fullname" . }}
        image: "{{ .Values.images.container.repository }}:{{ .Values.images.container.tag }}"
        args:
          - mount
          - "{{ .Values.rclone.remote }}"
          - "{{ .Values.rclone.path }}"
          - --config=/etc/rclone/rclone.conf
          - --cache-dir={{ .Values.rclone.cacheDir }}
          # - --allow-non-empty
          - --allow-other
        {{- range .Values.rclone.mountArgs }}
          - {{ . }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","fusermount -uz {{ .Values.rclone.path }}"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/rclone
        - name: cache
          mountPath: "{{ .Values.rclone.cacheDir }}"
        - name: data
          mountPath: "{{ .Values.rclone.path }}"
          mountPropagation: Bidirectional
      volumes:
      - name: config
        emptyDir: {}
      - name: rclone-config
        secret:
          secretName: {{ .Values.rclone.configSecretName }}
          optional: false
      - name: cache
        hostPath:
          path: "{{ .Values.rclone.cacheDir }}"
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: "{{ .Values.rclone.path }}"
          type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}