---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rclone-hostpath.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "rclone-hostpath.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rclone-hostpath.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rclone-hostpath.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      # initContainers:
      # - name: {{ .Chart.Name }}-config
      #   image: "{{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}"
      #   command:
      #     - cp
      #   args:
      #     - -v
      #     - /in/rclone.conf
      #     - /out/rclone.conf
      #   volumeMounts:
      #   - name: config-data
      #     mountPath: /in
      #     readOnly: true
      #   - name: config
      #     mountPath: /out
      # terminationGracePeriodSeconds: 120
      containers:
      - name: {{ .Chart.Name }}-rclone
        image: "{{ .Values.images.container.repository }}:{{ .Values.images.container.tag }}"
        args:
          - mount
          - "{{ .Values.rclone.remote }}:{{ .Values.rclone.subPath }}"
          - "{{ .Values.rclone.path }}/{{ .Values.rclone.subPath }}"
          - --config=/etc/rclone/rclone.conf
          - --allow-non-empty
          - --allow-other
        {{- range .Values.rclone.mountArgs }}
          - {{ . }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","fusermount -uz {{ .Values.rclone.path }}/{{ .Values.rclone.subPath }}"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: rclone-config
          mountPath: /etc/rclone
        - name: rclone-data
          mountPath: /var/lib/rclone
        - name: data
          mountPath: {{ .Values.rclone.path }}/{{ .Values.rclone.subPath }}
          mountPropagation: Bidirectional
      volumes:
      # - name: config
      #   emptyDir: {}
      - name: rclone-config
        secret:
          secretName: {{ .Values.rclone.configSecretName }}
          optional: false
      - name: data
        hostPath:
          path: {{ .Values.rclone.path }}/{{ .Values.rclone.subPath }}
          type: DirectoryOrCreate
      - name: rclone-data
        hostPath:
          path: {{ .Values.rclone.dataDir }}
          type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}